Merge api-v2-compatibility branch

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -416,6 +416,7 @@ deploy master:
     - echo $TEST_SETTINGS | base64 -d > test_settings.py
   dependencies: []
 
+# API Integration tests #
 
 .api_test_template: &api_test_template
   <<: *test_template
@@ -455,6 +456,8 @@ API:main:volumes: *api_test_template
     when: on_failure
   tags:
     - chrome
+
+# UI Integration tests #
 
 UI:clouds-add-1/2: *ui_test_template
 UI:clouds-add-2/2: *ui_test_template
@@ -497,6 +500,8 @@ UI:ip-whitelisting:
   <<: *ui_test_template
   retry: 1
 
+# Machine Provisioning tests #
+
 .multiprovisioning_test_template: &multiprovisioning_test_template
   <<: *test_template
   script:
@@ -512,19 +517,26 @@ UI:ip-whitelisting:
     - chrome
   when: manual
 
+MP:aliyun-machine-create: *multiprovisioning_test_template
+MP:azure-machine-create: *multiprovisioning_test_template
+MP:digital-ocean-machine-create: *multiprovisioning_test_template
+MP:ec2-machine-create: *multiprovisioning_test_template
+MP:gce-machine-create: *multiprovisioning_test_template
+MP:kubevirt-machine-create: *multiprovisioning_test_template
+MP:kvm-machine-create: *multiprovisioning_test_template
+MP:linode-machine-create: *multiprovisioning_test_template
+MP:lxd-machine-create: *multiprovisioning_test_template
+# MP:openstack-machine-create: *multiprovisioning_test_template
+MP:packet-machine-create: *multiprovisioning_test_template
+MP:rackspace-machine-create: *multiprovisioning_test_template
 
-MP:aliyun-provisioning: *multiprovisioning_test_template
-MP:azure-provisioning: *multiprovisioning_test_template
-MP:digital-ocean-provisioning: *multiprovisioning_test_template
-MP:ec2-provisioning: *multiprovisioning_test_template
-MP:gce-provisioning: *multiprovisioning_test_template
-MP:kvm-provisioning: *multiprovisioning_test_template
-MP:linode-provisioning: *multiprovisioning_test_template
-# MP:openstack-provisioning: *multiprovisioning_test_template
-MP:packet-provisioning: *multiprovisioning_test_template
-MP:rackspace-provisioning: *multiprovisioning_test_template
-
-# MP:volumes-provisioning: *multiprovisioning_test_template
+# Machine Provisioning tests #
+VP:aliyun-volume-create: *multiprovisioning_test_template
+VP:azure-volume-create: *multiprovisioning_test_template
+VP:digital-ocean-volume-create: *multiprovisioning_test_template
+VP:ec2-volume-create: *multiprovisioning_test_template
+VP:gce-volume-create: *multiprovisioning_test_template
+# VP:openstack-volume-create: *multiprovisioning_test_template
 #################### UNDEPLOY STAGE ####################
 
 .undeploy_template: &undeploy_template
@@ -595,3 +607,95 @@ prerelease:
   only:
     # only for references that match a prelease version string (v1.2.3-beta)
     - /^v\d+\.\d+\.\d+-.+$/
+
+helm_chart_release:
+  stage: release
+  image: mist/helm-automation
+
+  script:
+    - |
+        #! /usr/bin/env bash
+
+        gcloud auth activate-service-account --key-file=$GCLOUD_SERVICE_KEY
+        set -o errexit
+        set -o nounset
+        set -o pipefail
+        readonly REPO_URL=https://mist-charts.storage.googleapis.com/
+        readonly GCS_BUCKET=gs://mist-charts
+
+        main() {
+          if ! sync_repo chart "$GCS_BUCKET" "$REPO_URL"; then
+              log_error "Not all charts could be packaged and synced!"
+          fi
+        }
+
+        sync_repo() {
+          local repo_dir="${1?Specify repo dir}"
+          local bucket="${2?Specify repo bucket}"
+          local repo_url="${3?Specify repo url}"
+          local sync_dir="${repo_dir}-sync"
+          local index_dir="${repo_dir}-index"
+
+          helm init --client-only
+
+          echo "Syncing repo '$repo_dir'..."
+
+          mkdir -p "$sync_dir"
+          mkdir -p "$index_dir"
+
+          # Disable cache in requests and responses
+          gsutil -m setmeta -h "Cache-Control:no-cache" "$bucket"/*.tgz
+          gsutil -m setmeta -h "Cache-Control:no-cache" "$bucket"/index.yaml
+
+          # Copy the index.yaml file from the bucket.
+          if ! gsutil cp "$bucket/index.yaml" "$index_dir/index.yaml"; then
+            log_error "Exiting because unable to copy index locally. Not safe to proceed."
+            exit 1
+          fi
+
+          local return_value=0
+
+          # Loop around each chart and package.
+          for dir in "$repo_dir"/*; do
+            if helm dependency build "$dir"; then
+              helm package --destination "$sync_dir" "$dir"
+            else
+              log_error "Problem building dependencies. Skipping packaging of '$dir'."
+              return_value=1
+            fi
+          done
+
+          if helm repo index --url "$repo_url" --merge "$index_dir/index.yaml" "$sync_dir"; then
+
+            # Move updated index.yaml to sync folder so we don't push the old one again
+            mv -f "$sync_dir/index.yaml" "$index_dir/index.yaml"
+
+            # Push all the local chart tarballs to the bucket.
+            gsutil -m rsync "$sync_dir" "$bucket"
+
+            # Make sure index.yaml is synced last
+            gsutil cp "$index_dir/index.yaml" "$bucket"
+
+          else
+            log_error "Exiting because unable to update index. Not safe to push update."
+            exit 1
+          fi
+
+          ls -l "$sync_dir"
+
+          return "$return_value"
+        }
+
+        log_error() {
+          printf '\e[31mERROR: %s\n\e[39m' "$1" >&2
+        }
+
+        main
+  when: manual
+  only:
+    # only for references that match a version string (v1.2.3)
+    - /^v\d+\.\d+\.\d+$/
+  dependencies: []
+  except:
+    # Except branches, meaning it'll only apply to git tags
+    - branches
