2

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,8 +1,19 @@
 variables:
   GET_SOURCES_ATTEMPTS: 3
+  DEPLOY_DOMAIN_SUFFIX: -mist-ce.review.mist.io
+  TEST_DEPLOY_DOMAIN_SUFFIX: -mist-ce.test.mist.io
+
+  # Possible values are CI_REGISTRY, EXT_REGISTRY, DOCKERHUB
+  DOCKERHUB_IMAGE: mist/mist-ce
+  COMPOSE_REGISTRY: DOCKERHUB
+  DEPLOY_REGISTRY: EXT_REGISTRY
+  # Set to empty string '' to disable.
+  DEPLOY_REGISTRY_AUTH: ''
+  # API & UI tests image
+  TESTS_IMAGE: $EXT_REGISTRY_IMAGE/tests:$CI_COMMIT_SHA
 
 stages:
-  - discover-submodules
+  - discover
   - build
   - deploy
   - test
@@ -10,168 +21,192 @@ stages:
   - release
 
 
-#################### DISCOVER-SUBMODULES STAGE ####################
-
-discover-submodules:
-  stage: discover-submodules
-  variables:
-    GIT_SUBMODULE_STRATEGY: recursive
+discover submodules:
+  stage: discover
+  image: alpine
+  before_script:
+    - apk add --no-cache git
   script:
-    # Will fetch to get all new branches for find-submodules.sh
-    - git fetch -p --recurse-submodules
-    - ./ci/find-submodules.sh -n
-    - cp ci/update-pipelines.sh update-pipelines
+    - |
+        git submodule status | \
+          sed 's/^[ +-]\([0-9a-f]*\) \([^ ]*\).*$/\1,\2/' > submodules.csv
   artifacts:
     paths:
-      - all-submodules.csv
-      - related-submodules.csv
-      - update-pipelines
-    expire_in: 3 days
-  tags:
-    - shell-docker-light
+      - submodules.csv
+    expire_in: 10 days
   dependencies: []
 
 
-#################### BUILD STAGE ####################
-
-# Wait for images we depend on to become available.
-
-.docker_wait_submodule_img_template: &docker_wait_submodule_img_template
+.dind_template: &docker_template
   stage: build
-  variables:
-    GIT_STRATEGY: none
-    NUM: "60"
-    SLEEP: "10"
-  script:
-    - SUBMODULE_SHA=$(grep ^$REPO, all-submodules.csv | cut -d, -f2)
-    - echo SUBMODULE_SHA is $SUBMODULE_SHA
-    - GCR_IMG="gcr.io/mist-ops/$IMG"
-    - DOCKERHUB_IMG="mist/$IMG"
-    - IMGTAG="$GCR_IMG:$SUBMODULE_SHA"
-    - echo IMTAG is $IMGTAG
-
-    - echo "Will pull docker image $IMGTAG"
-    - for i in $(seq 1 $NUM); do docker pull $IMGTAG && OK=1 && break || sleep $SLEEP; done
-    - if [ -z "$OK" ]; then echo "ERROR Couldn't pull $IMGTAG!" && exit 1; fi
-
+  image: docker:latest
+  services:
+    - docker:dind
+  variables: &docker_variables
+    DOCKER_DRIVER: overlay2
+    DOCKER_HOST: "tcp://localhost:2375"
+  retry: 2
+  before_script:
+    # Configure registries.
     - |
-        for img_name in $GCR_IMG $DOCKERHUB_IMG; do
-          for ref in $CI_COMMIT_SHA $CI_COMMIT_REF_SLUG; do
-            IMGTAG2=$img_name:io-$ref
-            echo "Will tag and push $IMGTAG2"
-            docker tag $IMGTAG $IMGTAG2
-            docker push $IMGTAG2
+        export REGISTRIES=""
+
+        # Login to gitlab docker registry.
+        if [ -n "$CI_REGISTRY_IMAGE" ]; then
+          echo "Logging in to gitlab registry."
+          docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" \
+            $CI_REGISTRY
+          export REGISTRIES="$REGISTRIES $CI_REGISTRY_IMAGE"
+          echo "Logged in to gitlab registry."
+        else
+          echo "No credentials provided for gitlab registry, skipping."
+        fi
+
+        # Login to other registry.
+        if [ -n "$EXT_REGISTRY" ] && \
+           [ -n "$EXT_REGISTRY_IMAGE" ] && \
+           [ -n "$EXT_REGISTRY_USER" ] && \
+           [ -n "$EXT_REGISTRY_PASSWORD" ]
+        then
+          echo "Logging in to $EXT_REGISTRY."
+          docker login -u "$EXT_REGISTRY_USER" -p "$EXT_REGISTRY_PASSWORD" \
+            "$EXT_REGISTRY"
+          export REGISTRIES="$REGISTRIES $EXT_REGISTRY_IMAGE"
+          echo "Logged in to $EXT_REGISTRY."
+        else
+          echo "No credentials provided for external registry, skipping."
+        fi
+
+        # Login to dockerhub.
+        if [ -n "$DOCKERHUB_IMAGE" ] && \
+           [ -n "$DOCKERHUB_USER" ] && \
+           [ -n "$DOCKERHUB_PASSWORD" ]
+        then
+          echo "Logging in to dockerhub."
+          docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
+          export REGISTRIES="$REGISTRIES $DOCKERHUB_IMAGE"
+          echo "Logged in to dockerhub."
+        else
+          echo "No credentials provided for dockerhub, skipping."
+        fi
+
+        # Check if any registry configured.
+        if [ -z "$REGISTRIES" ]; then
+          echo "No registries configured, exiting."
+          exit 1
+        fi
+    - |
+        function docker_pull() {
+          # docker_pull <img> : Will retry several times to pull image.
+          img=$1
+          tries=60
+          sleep=10
+          echo "Will try to pull image $img ($tries tries, ${sleep}s sleep)."
+          for i in $(seq 1 $tries); do
+            if docker pull $img; then
+              echo "Image $img pulled successfully!"
+              return 0
+            fi
+            sleep $sleep
           done
-        done
-  tags:
-    - shell-docker-light
-  dependencies:
-    - discover-submodules
-
-wait-ui-image:
-  <<: *docker_wait_submodule_img_template
-  before_script:
-    - REPO=mistio/mist.ui
-    - IMG=ui
-
-wait-landing-image:
-  <<: *docker_wait_submodule_img_template
-  before_script:
-    - REPO=mistio/mist.landing
-    - IMG=landing
-
-wait-tests-image:
-  <<: *docker_wait_submodule_img_template
-  before_script:
-    - REPO=mistio/mist.tests
-    - IMG=tests_base
-
-
-# Rebuild api image.
-
-rebuild-api-image:
-  stage: build
-  variables:
-    NUM: "60"
-    SLEEP: "10"
-    REPO: mistio/mist.api
-    IMG: mist
-  script:
-    - SUBMODULE_SHA=$(grep ^$REPO, all-submodules.csv | cut -d, -f2)
-    - echo SUBMODULE_SHA is $SUBMODULE_SHA
-    - GCR_IMG="gcr.io/mist-ops/$IMG"
-    - DOCKERHUB_IMG="mist/$IMG"
-    - IMGTAG="$GCR_IMG:$SUBMODULE_SHA"
-    - echo IMTAG is $IMGTAG
-
-    - echo "Will pull docker image $IMGTAG"
-    - for i in $(seq 1 $NUM); do docker pull $IMGTAG && OK=1 && break || sleep $SLEEP; done
-    - if [ -z "$OK" ]; then echo "ERROR Couldn't pull $IMGTAG!" && exit 1; fi
-
-    - echo "Will rebuild api image"
-    - sed -i "s~^FROM.*~FROM $IMGTAG~" docker/mist/Dockerfile
-    - docker build -t $IMG/io-$CI_COMMIT_SHA --build-arg IO_VERSION_SHA=$CI_COMMIT_SHA --build-arg IO_VERSION_NAME=$CI_COMMIT_REF_NAME docker/mist
-
+          echo "Failed too pull image $img."
+          return 1
+        }
     - |
-        for img_name in $GCR_IMG $DOCKERHUB_IMG; do
-          for ref in $CI_COMMIT_SHA $CI_COMMIT_REF_SLUG; do
-            IMGTAG2=$img_name:io-$ref
-            echo "Will tag and push $IMGTAG2"
-            docker tag $IMG/io-$CI_COMMIT_SHA $IMGTAG2
-            docker push $IMGTAG2
-          done
-        done
-  tags:
-    - shell-docker-light
-  dependencies:
-    - discover-submodules
-
-
-# Build secondary images needed for deploying. Tag with SHA and branch name.
-
-.docker_build_img_template: &docker_build_img_template
-  stage: build
-  script:
-    - GCR_IMG="gcr.io/mist-ops/$IMG"
-    - DOCKERHUB_IMG="mist/$IMG"
-    - IMGTAG="$GCR_IMG:$CI_COMMIT_SHA"
-    - echo "Will build $IMGTAG"
-    - cd docker/$IMG
-    - docker build --pull -t $IMGTAG .
-    - |
-        for img_name in $GCR_IMG $DOCKERHUB_IMG; do
-          for ref in $CI_COMMIT_SHA $CI_COMMIT_REF_SLUG; do
-            for prefix in "io-" ""; do
-              IMGTAG2=$img_name:$prefix$ref
-              echo "Will tag and push $IMGTAG2"
-              docker tag $IMGTAG $IMGTAG2
-              docker push $IMGTAG2
+        function docker_push() {
+          # docker_push <src> <dest>: Retag and push image
+          # <src> must be the full name of a local image.
+          # <dest> must be just the image identifier, registry and tag will be
+          # added automatically.
+          tags="$CI_COMMIT_SHA $CI_COMMIT_REF_SLUG"
+          if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
+            tags="$tags latest"
+          fi
+          src=$1
+          for registry in $REGISTRIES; do
+            for tag in $tags; do
+              dest="$registry/$2:$tag"
+              echo "Tagging image $src as $dest..."
+              docker tag $src $dest
+              echo "Pushing image $dest..."
+              docker push $dest
             done
           done
-        done
-  tags:
-    - builder
+        }
+    - |
+        function get_submodule_sha() {
+          cat submodules.csv | grep ",$1$" | cut -d, -f1
+        }
+    - |
+        function docker_retag_submodule() {
+          repo=$1
+          img=$2
+          src_img="$img:$(get_submodule_sha $repo)"
+          docker_pull $src_img
+          docker_push $src_img $repo
+        }
+  dependencies:
+    - discover submodules
+
+.docker_retag_template: &docker_retag_template
+  <<: *docker_template
+  variables:
+    <<: *docker_variables
+    GIT_STRATEGY: none
+  script:
+    - export submodule=$(echo "$CI_JOB_NAME" | cut -d " " -f2)
+    - export orig_image=$(echo "$CI_JOB_NAME" | cut -d " " -f3)
+    - export orig_image=${orig_image:-$submodule}
+    - docker_retag_submodule $submodule mist/$orig_image
+
+retag landing: *docker_retag_template
+retag ui: *docker_retag_template
+retag tests tests_base: *docker_retag_template
+
+build api:
+  <<: *docker_template
+  script:
+    - SRC_IMG="mist/mist:$(get_submodule_sha api)"
+    - docker_pull $SRC_IMG
+    - |
+        docker build \
+          -t $CI_PROJECT_NAME/api:$CI_COMMIT_SHA \
+          --build-arg FROM_IMAGE=$SRC_IMG \
+          --build-arg MIST_VERSION_SHA=$CI_COMMIT_SHA \
+          --build-arg MIST_VERSION_NAME=$CI_COMMIT_REF_NAME \
+          docker/api
+    - docker_push $CI_PROJECT_NAME/api:$CI_COMMIT_SHA api
+
+.docker_build_template: &docker_build_template
+  <<: *docker_template
+  script:
+    - export img=$(echo "$CI_JOB_NAME" | cut -d " " -f2)
+    - docker build -t $CI_PROJECT_NAME/$img:$CI_COMMIT_SHA docker/$img
+    - docker_push $CI_PROJECT_NAME/$img:$CI_COMMIT_SHA $img
   dependencies: []
 
-build-nginx:
-  <<: *docker_build_img_template
-  variables:
-    IMG: nginx
+build nginx: *docker_build_template
+build gocky: *docker_build_template
+build logstash: *docker_build_template
+build elasticsearch-manage: *docker_build_template
 
-build-logstash:
-  <<: *docker_build_img_template
-  variables:
-    IMG: logstash
-
-build-elasticsearch-manage:
-  <<: *docker_build_img_template
-  variables:
-    IMG: elasticsearch-manage
-
-build-gocky:
-  <<: *docker_build_img_template
-  variables:
-    IMG: gocky
+compose:
+  stage: build
+  image: python:alpine
+  before_script:
+    - pip install docker-compose
+    - apk add --no-cache gettext
+  script:
+    - mkdir -p artifacts
+    - export IMG_REGISTRY=$(eval \$${COMPOSE_REGISTRY}_IMAGE)
+    - echo "IMG_REGISTRY=$IMG_REGISTRY"
+    - export IMG_TAG=$CI_COMMIT_REF_SLUG
+    - echo "IMG_TAG=$IMG_TAG"
+    - envsubst < docker-compose.yml > artifacts/docker-compose.yml
+  artifacts:
+    paths:
+      - artifacts/docker-compose.yml
+  dependencies: []
 
 
 #################### DEPLOY STAGE ####################
@@ -212,35 +247,29 @@ deploy_test_env:
 
 .test_template: &test_template
   stage: test
-  image: gcr.io/mist-ops/tests_base:io-$CI_COMMIT_SHA
+  image: $TESTS_IMAGE
   variables:
     GIT_STRATEGY: none
-    MIST_URL: http://$CI_COMMIT_REF_SLUG.io.test.ops.mist.io
+    MIST_URL: http://$CI_COMMIT_REF_SLUG$TEST_DEPLOY_DOMAIN_SUFFIX
     DISPLAY: ":1.0"
     REGISTER_USER_BEFORE_FEATURE: "True"
     EMAIL: thingirl.tester.mist.io+${CI_JOB_ID}@gmail.com
-  dependencies:
-    - discover-submodules
   before_script:
     - 'export TEST=$(echo "$CI_JOB_NAME" | cut -d/ -f1 | cut -d: -f2,3 | tr : /)'
     - echo "Test argument is $TEST"
-    - ./update-pipelines -n io:$CI_JOB_NAME running
+    - echo "Image used is $TESTS_IMAGE"
     - echo $TEST_SETTINGS | base64 -d > test_settings.py
-    - cat test_settings.py
+  dependencies: []
 
 .api_test_template: &api_test_template
   <<: *test_template
   script:
-    - /mist.tests/prepare_env.py --api -s /mist.tests/misttests/integration/api/$TEST.py || export FAILED=1
-    - ./update-pipelines -n io:$CI_JOB_NAME result
-  tags:
-    - kube-default
+    - /mist.tests/prepare_env.py --api -s /mist.tests/misttests/integration/api/$TEST.py
 
 .ui_test_template: &ui_test_template
   <<: *test_template
   script:
-    - /mist.tests/prepare_env.py -k --stop --tags=$TEST /mist.tests/misttests/integration/gui/core/pr/features || export FAILED=1
-    - ./update-pipelines -n io:$CI_JOB_NAME result
+    - /mist.tests/prepare_env.py -k --stop --tags=$TEST /mist.tests/misttests/integration/gui/core/pr/features
   artifacts:
     paths:
       - js_console.log
@@ -249,7 +278,7 @@ deploy_test_env:
     expire_in: 3 days
     when: on_failure
   tags:
-    - cpu
+    - shm
 
 
 API:io:api_token: *api_test_template
